FROM node:20

RUN apt-get update
RUN npm install -g @angular/cli
RUN ng version

WORKDIR /tmp

RUN git clone https://github.com/krekab16/Progrendszerek.git

WORKDIR /tmp/Progrendszerek/client

RUN npm install

RUN npm run build

EXPOSE 4200

CMD ["ng", "serve", "--host", "0.0.0.0"]
