FROM node:20

RUN apt-get update && apt-get install -y openssh-server && apt-get clean

RUN npm install -g pm2

RUN mkdir /var/run/sshd
RUN echo 'root:dockerpassword' | chpasswd
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

RUN groupadd -r deploy && useradd -m -r -g deploy deploy
RUN echo 'deploy:deploypassword' | chpasswd
RUN mkdir -p /app && chown deploy:deploy /app

RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

COPY keys/jenkins_deploy_key.pub /tmp/jenkins_deploy_key.pub
RUN mkdir -p /home/deploy/.ssh && \
    cat /tmp/jenkins_deploy_key.pub >> /home/deploy/.ssh/authorized_keys && \
    chown -R deploy:deploy /home/deploy/.ssh && \
    chmod 700 /home/deploy/.ssh && \
    chmod 600 /home/deploy/.ssh/authorized_keys && \
    rm /tmp/jenkins_deploy_key.pub

WORKDIR /app

EXPOSE 3000 22

CMD ["/bin/bash", "-c", "/usr/sbin/sshd && /bin/bash"]