apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-nodejs-sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-nodejs-sample-app
  template:
    metadata:
      labels:
        app: kubernetes-nodejs-sample-app
    spec:
      containers:
      - name: kubernetes-nodejs-sample-app
        image: kubernetes-nodejs-sample-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"