FROM node:20

RUN npm install -g pm2

WORKDIR /app

RUN git clone https://github.com/krekab16/sample-app-for-devops.git
WORKDIR /app/sample-app-for-devops
RUN git checkout feature/http-server
RUN npm install
RUN npm run build

EXPOSE 3000

ENTRYPOINT ["pm2-runtime", "start", "dist/index.js", "--name", "'calculator-app'"]