apiVersion: v1
kind: Service
metadata:
  name: kubernetes-nodejs-sample-app-service
spec:
  selector:
    app: kubernetes-nodejs-sample-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer